# Site configuration data
navigation:
  - name: "Home"
    url: "/"
  - name: "Features"
    url: "/features/"
  - name: "Blog"
    url: "/blog/"
  - name: "About"
    url: "/about/"
  - name: "Contact"
    url: "/contact/"

social_links:
  - name: "Twitter"
    url: "https://twitter.com/AstroAuraApp"
    icon: "fab fa-twitter"
  - name: "GitHub"
    url: "https://github.com/astroaura"
    icon: "fab fa-github"
  - name: "RSS"
    url: "/feed.xml"
    icon: "fas fa-rss"

app_stores:
  - name: "Google Play"
    url: "#"
    image: "/assets/images/google-play-badge.png"
    alt: "Get it on Google Play"

features:
  - title: "AI-Powered Insights"
    description: "Get personalized astrological insights powered by advanced AI algorithms"
    icon: "fas fa-brain"
  - title: "11 Languages"
    description: "Access cosmic wisdom in your native language with our multilingual support"
    icon: "fas fa-globe"
  - title: "Real-time Calculations"
    description: "Accurate birth charts and planetary positions calculated in real-time"
    icon: "fas fa-calculator"
  - title: "Tarot Integration"
    description: "Combine astrology with tarot for deeper spiritual insights"
    icon: "fas fa-cards"
  - title: "Cosmic Weather"
    description: "Stay updated with current planetary transits and their meanings"
    icon: "fas fa-cloud-sun"
  - title: "Community Insights"
    description: "Connect with fellow cosmic explorers and share experiences"
    icon: "fas fa-users"

trust_indicators:
  - number: "4.9"
    label: "App Store Rating"
    icon: "fas fa-star"
  - number: "15k+"
    label: "Happy Users"
    icon: "fas fa-users"
  - number: "11"
    label: "Languages"
    icon: "fas fa-globe"
  - number: "24/7"
    label: "Cosmic Insights"
    icon: "fas fa-moon"